/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeeStructureRouteImport } from './routes/fee-structure'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as AdmissionsApplyRouteImport } from './routes/admissions.apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeStructureRoute = FeeStructureRouteImport.update({
  id: '/fee-structure',
  path: '/fee-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsApplyRoute = AdmissionsApplyRouteImport.update({
  id: '/admissions/apply',
  path: '/admissions/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/fee-structure': typeof FeeStructureRoute
  '/teachers': typeof TeachersRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/fee-structure': typeof FeeStructureRoute
  '/teachers': typeof TeachersRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/fee-structure': typeof FeeStructureRoute
  '/teachers': typeof TeachersRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/fee-structure'
    | '/teachers'
    | '/admissions/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/fee-structure'
    | '/teachers'
    | '/admissions/apply'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/fee-structure'
    | '/teachers'
    | '/admissions/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  ContactRoute: typeof ContactRoute
  FeeStructureRoute: typeof FeeStructureRoute
  TeachersRoute: typeof TeachersRoute
  AdmissionsApplyRoute: typeof AdmissionsApplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-structure': {
      id: '/fee-structure'
      path: '/fee-structure'
      fullPath: '/fee-structure'
      preLoaderRoute: typeof FeeStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/apply': {
      id: '/admissions/apply'
      path: '/admissions/apply'
      fullPath: '/admissions/apply'
      preLoaderRoute: typeof AdmissionsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  ContactRoute: ContactRoute,
  FeeStructureRoute: FeeStructureRoute,
  TeachersRoute: TeachersRoute,
  AdmissionsApplyRoute: AdmissionsApplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
